import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import BootstrapClient from '../components/BootstrapClient';
import type { Metadata } from "next";
import Navbar from "../components/NavBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VenueStart",
  description: "Generated by create next app",
  icons: "/venue-start-icon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <main>{children}</main>
        <BootstrapClient />
      </body>
    </html>
  );
}
