import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";

import {
  Geist,
  Geist_Mono,
  Montserrat,
  Playfair_Display,
} from "next/font/google";

import BootstrapClient from "../lib/bootstrap-client";
import Footer from "../components/footer";
import type { Metadata } from "next";
import Navbar from "../components/nav-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust as needed
});

// Playfair Display
const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust as needed
});
export const metadata: Metadata = {
  title: "VenueStart",
  description: "Generated by create next app",
  icons: "/venue-start-icon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${playfair.variable}`}>
        <Navbar />
        <main>{children}</main>
        <BootstrapClient />
        <Footer />
      </body>
    </html>
  );
}
